pull_request_rules:
  - name: Automatic merge for adding new package
    conditions:
      - "#files=1"
      - "files~=data/packages/(.*)\\.yml$"
      - "-files~=data/packages/(.*)(google|unity|microsoft|apple|meta|oculus|twitter)\\.(.*)\\.yml$"
      - "#files=1"
      - -conflict
      - "status-success~=CI"
      - or:
        - "title~=^chore\\(data\\): new package"
        - "title~=^Create(.*)\\.yml$"

    actions:
      merge:
        method: merge
      comment:
        message: "Thank you for contributing to the OpenUPM platform. 🤟 The build pipelines may need up to 30 minutes to import the package and make it available on the website."
