name: CI

on: [push, pull_request]

jobs:
  validate-data:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, 'skip ci') }}
    name: Data validation
    steps:
    - uses: actions/checkout@v4
    - name: set node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: npm
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
